SET search_path = norwestproduce, pg_temp;

CREATE TABLE IF NOT EXISTS customer_payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_code text NOT NULL DEFAULT 'USA',
  sale_id integer NOT NULL REFERENCES sales(id),
  customer text NOT NULL,
  payment_date text NOT NULL,
  amount double precision NOT NULL CHECK (amount > 0),
  method text NOT NULL DEFAULT 'OTRO',
  reference text,
  notes text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE INDEX IF NOT EXISTS customer_payments_org_sale_idx ON customer_payments (organization_code, sale_id);
CREATE INDEX IF NOT EXISTS customer_payments_org_date_idx ON customer_payments (organization_code, payment_date);
